Cleanup patch-export bugs

diff --git a/patches/opnfv-fuel/0003-Add-arm64-deb-repositories-setup.patch b/patches/opnfv-fuel/0003-Add-arm64-deb-repositories-setup.patch
--- a/patches/opnfv-fuel/0003-Add-arm64-deb-repositories-setup.patch
+++ b/patches/opnfv-fuel/0003-Add-arm64-deb-repositories-setup.patch
@@ -8,8 +8,8 @@ Subject: [PATCH] Add arm64 deb repositories setup
  build/install/apt-ftparchive-release.conf |  2 +-
  build/install/apt-ftparchive-udeb.conf    |  7 ++++++-
  build/install/install.sh                  | 22 ++++++++++++++++++----
- build/install/uninstall.sh                | 20 +++++++++++---------
- 6 files changed, 44 insertions(+), 16 deletions(-)
+ build/install/uninstall.sh                | 18 ++++++++++--------
+ 6 files changed, 43 insertions(+), 15 deletions(-)
 
 diff --git a/build/f_isoroot/f_kscfg/ks.cfg b/build/f_isoroot/f_kscfg/ks.cfg
 index c93babe..30bad1d 100644
@@ -126,7 +126,7 @@ index 4e0389e..8c29e08 100755
      cp -Rvp $DEST/etc/puppet $DEST/etc/puppet.backup
  }
 diff --git a/build/install/uninstall.sh b/build/install/uninstall.sh
-index a9e74bc..0266e17 100755
+index a9e74bc..e90c632 100755
 --- a/build/install/uninstall.sh
 +++ b/build/install/uninstall.sh
 @@ -31,15 +31,17 @@ DEST=$MOUNT
@@ -137,17 +137,16 @@ index a9e74bc..0266e17 100755
 -    echo "Error - didn't find backup file for Packages!"
 -    exit 1
 -fi
--
--if [ ! -f  $REPO/dists/trusty/main/binary-amd64/Packages.gz.backup ]; then
--    echo "Error - didn't find backup file for Packages.gz!"
--    exit 1
--fi
 +for arch in arm64 amd64; do
 +    if [ ! -f  $REPO/dists/trusty/main/binary-${arch}/Packages.backup ]; then
 +        echo "Error - didn't find backup file for Packages for ${arch}!"
 +        exit 1
 +    fi
-+
+ 
+-if [ ! -f  $REPO/dists/trusty/main/binary-amd64/Packages.gz.backup ]; then
+-    echo "Error - didn't find backup file for Packages.gz!"
+-    exit 1
+-fi
 +    if [ ! -f  $REPO/dists/trusty/main/binary-${arch}/Packages.gz.backup ]; then
 +        echo "Error - didn't find backup file for Packages.gz for ${arch}!"
 +        exit 1
